[package]
name = "ncog"
version = "0.1.0"
edition = "2018"

[dependencies]
bonsaidb = { path = "../../bonsaidb/bonsaidb", features = [
    "server-full",
    "client-full",
    "cli",
] }
ncog-encryption = { path = "../ncog-encryption" }
time = { version = "0.3", features = ["std", "formatting", "serde"] }
serde = { version = "1", features = ["derive"] }
