name: Clippy

on: [push]

jobs:
  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Build tests
        run: |
          cargo clippy -- -D warnings